// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFOGt_RiMSkfyeq_IoPOlkc2y-xd3mAEY',
    appId: '1:115834614541:web:a67e86057c83229b737644',
    messagingSenderId: '115834614541',
    projectId: 'authtutorial-60a9d',
    authDomain: 'authtutorial-60a9d.firebaseapp.com',
    storageBucket: 'authtutorial-60a9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPzTNNsQs-kf-PIKyABEqma-T110ZNc38',
    appId: '1:115834614541:android:12856ab1d10ea190737644',
    messagingSenderId: '115834614541',
    projectId: 'authtutorial-60a9d',
    storageBucket: 'authtutorial-60a9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZgtxPuFkK7NycFEmhvaT4K-DQgNfMfQs',
    appId: '1:115834614541:ios:1bcbfb8222bc20cd737644',
    messagingSenderId: '115834614541',
    projectId: 'authtutorial-60a9d',
    storageBucket: 'authtutorial-60a9d.appspot.com',
    iosClientId:
        '115834614541-o5k9kjjk0udor2355sosqpo2vva55u2n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterUiLoginLogoutEmail',
  );
}
